### ISSUE TITLE
Issue while running app.py

### ISSUE THREAD

**Issue by swatitupat123** [SurajSubramanian/Emotion-and-Activity-Detection#1]
The app.py is failing while running throws the error for retina-face module.
The module is not getting installed as well.

Any solution for this ?

**Comment by surajsubramanian** [comment]
The repository is no longer maintained.
> The app.py is failing while running throws the error for retina-face module

Moreover above information is insufficient for me to suggest possible bugs in the code/fixes in your setup.

Feel free to create a PR if you solve the issue, good luck!
